name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
                  cache-dependency-path: ./pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install

            - name: Run Biome
              run: pnpm biome ci .

            - name: Build project
              run: pnpm build --verbose
