name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install npm dependencies
              uses: bahmutov/npm-install@v1

            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.4.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Biome
              run: npm exec biome ci .

            - name: Compile
              run: npm run compile --verbose
