name: Publish @next

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"

jobs:
    check:
        if: github.repository == 'paradoxuum/commander' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        outputs:
            version: ${{ env.VERSION }}
            version_changed: ${{ env.VERSION_CHANGED }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set version
              run: |
                  echo "VERSION=$(cat package.json | jq -r .version)-dev.$(git rev-parse --short HEAD)" >> $GITHUB_ENV
                  npm version --no-git-tag-version ${{ env.VERSION }}

            - name: Check version
              run: |
                  LATEST_VERSION=$(curl --silent https://registry.npmjs.org/@rbxts/commander | jq -r '."dist-tags" | .next')
                  echo "VERSION_CHANGED=$(test ${{ env.VERSION }} != $LATEST_VERSION && echo true || echo false)" >> $GITHUB_ENV

    publish:
        runs-on: ubuntu-latest
        needs: check
        if: needs.check.outputs.version_changed == 'true'
        env:
            VERSION: ${{ needs.check.outputs.version }}
        permissions:
            id-token: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install npm Dependencies
              uses: bahmutov/npm-install@v1

            - name: Set version
              run: npm version --no-git-tag-version ${{ env.VERSION }}

            - name: Publish @next
              run: npm publish --tag next --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
